/**
 * Approval gate + whitelisted execution.
 *
 * Two hard rules encoded here:
 *  1. An intervention cannot leave INTERVENING without an explicit human
 *     approval record (who and when). There is no auto-approve path, not even
 *     for tests — tests must pass `acknowledgedBy` too.
 *  2. `executeIntervention` can only emit a checklist. It physically cannot run
 *     a shell command, because it never receives one.
 */

import type { Intervention, InterventionStep } from "../shared/schemas/intervention.js";

export class ApprovalRequiredError extends Error {
  constructor(interventionId: string) {
    super(`Intervention ${interventionId} requires explicit human approval before execution`);
    this.name = "ApprovalRequiredError";
  }
}

export interface ApprovalRequest {
  interventionId: string;
  /** Who is acknowledging. Anything but a non-empty string is rejected. */
  acknowledgedBy: string;
  decision: "approved" | "rejected";
  note?: string;
  at?: string;
}

/** Actions the executor is permitted to perform. Everything else is "manual". */
export const ALLOWED_ACTIONS = ["manual", "render_checklist", "export_todo"] as const;
export type AllowedAction = (typeof ALLOWED_ACTIONS)[number];

export function isAllowedAction(a: string): a is AllowedAction {
  return (ALLOWED_ACTIONS as readonly string[]).includes(a);
}

export interface ApprovalResult {
  intervention: Intervention;
  /** True when the approval actually changed the record. */
  changed: boolean;
}

/**
 * Record a human decision. Rejects a blank acknowledger: an unattributed
 * approval is indistinguishable from the agent approving itself.
 */
export function reviewIntervention(intervention: Intervention, req: ApprovalRequest): ApprovalResult {
  const by = req.acknowledgedBy?.trim();
  if (!by) throw new Error("acknowledgedBy must be a non-empty human identifier");
  if (intervention.approval.status !== "pending") {
    return { intervention, changed: false };
  }
  const at = req.at ?? new Date().toISOString();
  return {
    intervention: {
      ...intervention,
      approval: { required: true, status: req.decision, by, at, note: req.note },
    },
    changed: true,
  };
}

export interface ExecutionOutcome {
  interventionId: string;
  /** Always a rendered artifact — never a side effect on the user's machine. */
  kind: "checklist" | "todo";
  title: string;
  items: Array<{ stepId: string; instruction: string; done: boolean }>;
  markdown: string;
}

/**
 * Render the approved intervention as a checklist. Fail closed when approval is
 * missing so a bug in the caller cannot skip the gate.
 */
export function executeIntervention(intervention: Intervention): ExecutionOutcome {
  if (intervention.approval.status !== "approved") {
    throw new ApprovalRequiredError(intervention.interventionId);
  }
  const disallowed = intervention.steps.filter((s) => !isAllowedAction(s.action));
  if (disallowed.length) {
    throw new Error(`Intervention contains non-whitelisted action(s): ${disallowed.map((s) => s.action).join(", ")}`);
  }
  const items = intervention.steps.map((s) => ({ stepId: s.stepId, instruction: s.instruction, done: false }));
  const markdown = [
    `## ${intervention.title}`,
    "",
    intervention.description,
    "",
    `**Target metric:** \`${intervention.targetMetric}\`  `,
    `**Approved by:** ${intervention.approval.by} at ${intervention.approval.at}`,
    "",
    ...items.map((i) => `- [ ] ${i.instruction}`),
    "",
    "_This checklist was generated by agent-canary. No action was taken on your machine._",
  ].join("\n");

  return {
    interventionId: intervention.interventionId,
    kind: "checklist",
    title: intervention.title,
    items,
    markdown,
  };
}

/** Guard used by the API so an unapproved intervention can never be "run". */
export function assertApprovable(intervention: Intervention): void {
  if (intervention.approval.status !== "approved") throw new ApprovalRequiredError(intervention.interventionId);
}

export function stepsForDisplay(steps: InterventionStep[]): Array<{ index: number; instruction: string }> {
  return steps.map((s, i) => ({ index: i + 1, instruction: s.instruction }));
}
